name = "astro-http"
   type = "webpack"
   account_id = "eb88d8d65950bb1c91396b64fd25c3cd"
   workers_dev = true
   route = ""
   zone_id = ""
   compatibility_date = "2023-10-30"

   [site]
   bucket = "./dist"
   entry-point = "workers-site"

   [build]
   command = "npm run build"
   upload.format = "service-worker"
