main = "workers-site/index.js"
name = "astro-http"
   account_id = "eb88d8d65950bb1c91396b64fd25c3cd"
   workers_dev = true
   compatibility_date = "2023-10-30"

   [site]
   bucket = "./dist"

   [build]
   command = "npm run build"   